apiVersion: apps/v1
kind: Deployment
metadata:
  name: juriscrape-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juriscrape-api
  template:
    metadata:
      labels:
        app: juriscrape-api
    spec:
      containers:
      - name: juriscrape-api
        image: brenoalberto/juriscrape-api
        env:
        - name: MONGO_URL
          value: "mongodb://juriscrape-mongo-srv:27017/juriscrape"
        # - name: TJ_CRAWLER_URL
        #   value: "http://juriscrape-crawlers-srv:3008"
        - name: TJAL_ESAJ_URL
          value: "http://juriscrape-tjal-esaj-srv:3008"
        - name: TJCE_ESAJ_URL
          value: "http://juriscrape-tjce-esaj-srv:3008"
        command: ["npm", "run", "dev"]
---
apiVersion: v1
kind: Service
metadata:
  name: juriscrape-api-srv
spec:
  selector:
    app: juriscrape-api
  ports:
  - name: juriscrape-api
    protocol: TCP
    port: 3000
    targetPort: 3000
